### ISSUE TITLE
Startscreen after exit

### ISSUE THREAD

**Issue by DaKie206** [MarkusMCPEGamer/Karambolage#30]
![image](https://user-images.githubusercontent.com/50425705/62618886-abd7a900-b915-11e9-8434-b60828f76a2d.png)

**Comment by DaKie206** [comment]
@MarkusMCPEGamer

**Comment by MarkusMCPEGamer** [comment]
Das Karambolage fehlt?

**Comment by DaKie206** [comment]
Nur ganz schwach

**Comment by MarkusMCPEGamer** [comment]
Bei mir nicht, fetch mal neusten master
