### ISSUE TITLE
Local Multiplayer

### ISSUE THREAD

**Issue by MarkusMCPEGamer** [MarkusMCPEGamer/Karambolage#36]

**Comment by DaKie206** [comment]
Wie soll der aussehen?

**Comment by MarkusMCPEGamer** [comment]
Man hat 2 Spieler. Den einen kontrollierbar mit WASD und den anderen mit den Pfeiltasten.

**Comment by MarkusMCPEGamer** [comment]
Mach das Sinn?

**Comment by DaKie206** [comment]
Und dann wer länger überlebt?

**Comment by MarkusMCPEGamer** [comment]
Ja, sowas. Ich habs nur mal vorgemerkt
Hat ein Freund von uns vorgeschlagen

**Comment by DaKie206** [comment]
Gut

**Comment by MarkusMCPEGamer** [comment]
Done! #55
