### ISSUE TITLE
Nur bugs

### ISSUE THREAD

**Issue by DaKie206** [MarkusMCPEGamer/Karambolage#4]
lol
-Timeout funktioniert nicht
![image](https://user-images.githubusercontent.com/50425705/62242532-a6d99d80-b3db-11e9-96b2-637e48cc49bb.png)
-Pausemenü funktioniert nicht
![image](https://user-images.githubusercontent.com/50425705/62242569-b9ec6d80-b3db-11e9-87f5-13d89881c84c.png)
-Lettertimer (oder so) fnktioniert nicht
![image](https://user-images.githubusercontent.com/50425705/62242663-f1f3b080-b3db-11e9-9b69-6427e55f91d6.png)

**Comment by MarkusMCPEGamer** [comment]
Im BETA Zweig? 🤔🙁

**Comment by DaKie206** [comment]
Nein master

**Comment by DaKie206** [comment]
Fixed in latest commit
