### ISSUE TITLE
Ghost at x:120 y:170?

### ISSUE THREAD

**Issue by MarkusMCPEGamer** [MarkusMCPEGamer/Karambolage#43]
The character is "lagging" at x:120 y:170!?

**Comment by DaKie206** [comment]
Warum noch offen wenn invalid?

**Comment by MarkusMCPEGamer** [comment]
Weil das noch nicht behoben wurde

**Comment by DaKie206** [comment]
Dann nicht invalid

**Comment by MarkusMCPEGamer** [comment]
Wiso nicht? Schaut doch nicht richtig aus

**Comment by DaKie206** [comment]
Das heißt dass das, das (3 das(s) (jetzt 4)) im issue steht nicht richtig ist. Was du meinst ist bug

**Comment by MarkusMCPEGamer** [comment]
Achso, ok :+1:

**Comment by MarkusMCPEGamer** [comment]
Fixed in #35
