### ISSUE TITLE
Convert "are you sure you want to close"-popup anim to tween animation

### ISSUE THREAD

**Issue by DaKie206** [MarkusMCPEGamer/Karambolage#46]
Make issues, please

**Comment by MarkusMCPEGamer** [comment]
Das war nur für mich eine notiz. Weil ich das noch machen wollte und es an diesem Abend nich mehr geschafft habe... Habs aber noch nicht gemacht...

**Comment by DaKie206** [comment]
Trotzdem

**Comment by MarkusMCPEGamer** [comment]
Was brigen denn die Notizen?

**Comment by DaKie206** [comment]
Gute Frage

**Comment by MarkusMCPEGamer** [comment]
.net

**Comment by DaKie206** [comment]
Was bedeutet teen?
Meinst du scene?

**Comment by MarkusMCPEGamer** [comment]
Done (almost) see #56
