### ISSUE TITLE
Bigger FOV for multiplayer

### ISSUE THREAD

**Issue by DaKie206** [MarkusMCPEGamer/Karambolage#65]
Just zoom out

**Comment by MarkusMCPEGamer** [comment]
Dann hat man einen schwarzen Rand...

**Comment by MarkusMCPEGamer** [comment]
![grafik](https://user-images.githubusercontent.com/45641704/64485370-4c283280-d220-11e9-8da6-420253e5b5fd.png)

**Comment by MarkusMCPEGamer** [comment]
Außerdem müsste man die Geschwindigkeiten und Größen verändern...

**Comment by DaKie206** [comment]
ok
